#!/usr/bin/env python3
"""Rebuild data.json's control library from recognized best-practice sources.

Curated from: ISO/IEC 42001:2023 Annex A (38 controls, A.2-A.10) · NIST AI RMF
1.0 functions & Playbook · CSA AI Controls Matrix v1 (18 domains) · OWASP Top 10
for LLM Applications 2025 + Agentic Applications 2026 (ASI01-10) · MITRE ATLAS
mitigations · Australia's Voluntary AI Safety Standard (10 guardrails) ·
OAIC/APRA/eSafety/DTA obligations already tracked in this corpus.

Each control: NIST function, ISO 42001 Annex A area, the risk theme it
addresses, implementation/testing/evidence guidance, framework crosswalk refs
(relatedStandards), primary sources, and a practice-lens soWhat.

Replaces data.json controls wholesale (previous set retained in git history
and data.backup-*.json). Idempotent.
"""
import json
import re
import unicodedata
from datetime import date
from pathlib import Path

DATA = Path(__file__).parent / "data.json"
TODAY = str(date.today())

SRC = {
    "iso": "https://www.iso.org/standard/42001",
    "nist": "https://www.nist.gov/itl/ai-risk-management-framework",
    "playbook": "https://airc.nist.gov/airmf-resources/playbook/",
    "aicm": "https://cloudsecurityalliance.org/artifacts/ai-controls-matrix-v1-1",
    "owasp_llm": "https://genai.owasp.org/resource/owasp-top-10-for-llm-applications-2025/",
    "owasp_asi": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/",
    "atlas": "https://atlas.mitre.org/mitigations",
    "vaiss": "https://www.industry.gov.au/publications/voluntary-ai-safety-standard/10-guardrails",
    "oaic": "https://www.oaic.gov.au/privacy/australian-privacy-principles",
    "apra": "https://www.apra.gov.au/news-and-publications/apra-letter-to-industry-artificial-intelligence-ai",
    "esafety": "https://www.esafety.gov.au/industry/regulatory-guidance",
    "dta": "https://www.dta.gov.au/ai-transparency-statement",
    "genai_profile": "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
    "c2pa": "https://c2pa.org/",
    "ssdf": "https://csrc.nist.gov/projects/ssdf",
}

# name, fn, area, risk (theme wording drives coverage), maturity, description,
# implementation, owner, testingMethod, frequency, evidenceRequired,
# relatedStandards (crosswalk refs), relatedTools, sources, soWhat
C = []
def ctl(name, fn, area, risk, maturity, desc, impl, owner, test, freq, evidence, refs, tools, sources, sowhat):
    C.append(dict(name=name, nistFunction=fn, iso42001Area=area, risk=risk,
                  maturity=maturity, description=desc, implementation=impl,
                  owner=owner, testingMethod=test, frequency=freq,
                  evidenceRequired=evidence, relatedStandards=refs,
                  relatedTools=tools, sources=sources, soWhat=sowhat))

A = {  # ISO area labels used by the site
    2: "A.2 AI policies", 3: "A.3 Internal organization", 4: "A.4 Resources",
    5: "A.5 Impact assessment", 6: "A.6 System life cycle", 7: "A.7 Data",
    8: "A.8 Interested-party info", 9: "A.9 Responsible use", 10: "A.10 Third parties",
}

# ═════════════════════════ GOVERN ═════════════════════════
ctl("AI policy, approved and reviewed", "GOVERN", A[2],
    "Governance and accountability risk from ungoverned AI adoption", "Established",
    "A management-approved policy for developing and using AI, aligned with organisational strategy, risk appetite, and other policies, reviewed on a defined cycle.",
    "Draft against ISO 42001 A.2; have the executive owner and board approve; publish internally; set an annual review trigger plus event-driven review on major regulatory change.",
    "Chief Risk Officer / Head of AI Governance",
    "Check approval records, version history, and review-cycle evidence; interview staff for awareness.",
    "Annual review",
    "Approved policy, review log, board minute",
    ["ISO 42001 A.2.2-A.2.4", "NIST AI RMF GOVERN 1", "AU VAISS Guardrail 1"],
    [], [SRC["iso"], SRC["vaiss"]],
    "The first artifact any auditor, regulator, or enterprise customer asks for — without it every other control looks improvised."),

ctl("AI acceptable-use standard for staff", "GOVERN", A[2],
    "Shadow AI and ungoverned adoption risk", "Established",
    "Rules for what staff may and may not do with AI tools: approved tools, prohibited data, disclosure expectations, and consequences.",
    "Publish an acceptable-use standard covering public chatbots, coding agents, and uploads of client or personal data; pair with an approved-tools register and a fast approval path so the safe route is the easy route.",
    "CISO / HR",
    "Sample staff attestations; test that prohibited flows (e.g. pasting client data into unapproved tools) are blocked or detected.",
    "Annual refresh; onboarding for all new staff",
    "Standard, attestation records, DLP alerts",
    ["ISO 42001 A.2.2 / A.9.2", "CSA AICM: Human Resources", "NIST AI RMF GOVERN 4"],
    [], [SRC["aicm"], SRC["iso"]],
    "Shadow AI is found in every engagement — an enforced acceptable-use standard plus an easy approval path is the control that actually changes behaviour."),

ctl("Named AI accountable executive and RACI", "GOVERN", A[3],
    "Governance and accountability risk", "Established",
    "A named senior owner for AI risk with documented roles and responsibilities across the AI life cycle, including who can approve, pause, or retire a system.",
    "Assign an accountable executive; build a RACI covering development, deployment, monitoring, and incident response; wire it into position descriptions and delegations.",
    "CEO / Board",
    "Verify the RACI exists, names real people, and matches delegations; test with a scenario walkthrough.",
    "Review on org change; at least annually",
    "RACI, delegation instrument, position descriptions",
    ["ISO 42001 A.3.2", "NIST AI RMF GOVERN 2", "AU VAISS Guardrail 1"],
    [], [SRC["iso"], SRC["vaiss"]],
    "APRA's central complaint is that no one owns AI risk — a named executive with a real RACI answers the board-accountability question before it's asked."),

ctl("AI concern and whistleblowing channel", "GOVERN", A[3],
    "Governance and safety-culture risk", "Emerging",
    "A protected route for staff to report AI concerns — unsafe behaviour, misuse, ethics issues — with triage and feedback loops.",
    "Extend the existing whistleblowing channel to explicitly cover AI concerns; train triage staff; report themes to the AI governance committee.",
    "Chief Risk Officer",
    "Test the channel end-to-end with a synthetic concern; check triage SLAs and closure records.",
    "Continuous; quarterly reporting",
    "Channel records, triage log, committee minutes",
    ["ISO 42001 A.3.3", "NIST AI RMF GOVERN 4.3"],
    [], [SRC["iso"]],
    "Frontier-lab incidents keep showing that staff knew first — a working concerns channel is cheap early warning."),

ctl("Board AI literacy and challenge programme", "GOVERN", A[3],
    "Board oversight and governance risk", "Emerging",
    "Structured board education on AI capability, risk, and obligations, so directors can credibly challenge management on AI decisions.",
    "Run board sessions on the AI inventory, top risks, and obligations calendar; provide a standing AI risk dashboard; document challenge in minutes.",
    "Company Secretary / CRO",
    "Review board papers and minutes for evidence of informed challenge.",
    "Half-yearly",
    "Board pack, minutes, attendance",
    ["NIST AI RMF GOVERN 2 / 3", "APRA CPS 510 direction", "AU VAISS Guardrail 1"],
    [], [SRC["apra"], SRC["vaiss"]],
    "Regulators now read board minutes for AI challenge — this control creates the evidence they're looking for."),

ctl("Regulatory obligations register and change watch", "GOVERN", A[2],
    "Regulatory fragmentation and compliance risk", "Established",
    "A living register of AI-relevant legal obligations (EU AI Act, APP 1 ADM, sector rules) with owners, deadlines, and a watch process for change.",
    "Stand up an obligations register keyed to jurisdictions and systems; assign owners; review the Horizon calendar monthly and re-baseline on regulatory change.",
    "General Counsel / Compliance",
    "Sample obligations for currency and ownership; reconcile against the compliance calendar.",
    "Monthly watch; quarterly full review",
    "Obligations register, review minutes, deadline calendar",
    ["ISO 42001 A.2.3", "NIST AI RMF GOVERN 1.1", "EU AI Act", "OAIC APP 1"],
    [], [SRC["oaic"], SRC["nist"]],
    "Turns regulatory noise into a dated work plan — the same artifact this site's Horizon section renders."),

ctl("AI conformity records and audit trail", "GOVERN", A[2],
    "Compliance evidence and audit-readiness risk", "Emerging",
    "Records demonstrating each guardrail and obligation is met, maintained so a third party could assess compliance without archaeology.",
    "Define an evidence map per obligation (what artifact, where, who maintains); store centrally with retention rules; index by system.",
    "Compliance / Internal Audit",
    "Pick three obligations and pull the evidence pack cold — time how long it takes.",
    "Continuous; annual audit",
    "Evidence index, sampled artifacts, audit report",
    ["AU VAISS Guardrail 9", "ISO 42001 Clause 9", "CSA AICM: Audit and Assurance"],
    [], [SRC["vaiss"], SRC["aicm"]],
    "The difference between being compliant and being able to prove it in a week — sell readiness assessments against this gap."),

ctl("AI transparency statement, published and maintained", "GOVERN", A[8],
    "Transparency and public-trust risk", "Established",
    "A public statement describing how the organisation uses AI, its safeguards, and contact points — mandatory for Australian government agencies, best practice elsewhere.",
    "Publish per the DTA policy pattern (uses, oversight, accountable official); refresh whenever material uses change; link from the privacy policy.",
    "Accountable AI executive",
    "Diff the statement against the AI inventory for coverage; check the update log.",
    "Review quarterly; update on material change",
    "Published statement, update log, inventory reconciliation",
    ["DTA AI transparency statement", "AU VAISS Guardrail 6", "ISO 42001 A.8.5"],
    [], [SRC["dta"], SRC["vaiss"]],
    "Agencies have the obligation; enterprises get the trust dividend — reconciling statement vs inventory is a fast, high-value review."),

ctl("ADM transparency disclosure (APP 1.7-1.9)", "GOVERN", A[8],
    "Regulatory compliance risk — automated decision-making", "Established",
    "Privacy-policy disclosure of the kinds of personal information used in automated decisions that affect rights or interests, and the kinds of decisions made — commencing 10 December 2026.",
    "Inventory ADM uses; classify which affect rights/interests; draft disclosures against OAIC guidance; update the privacy policy before commencement.",
    "Privacy Officer",
    "Trace each rights-affecting ADM use to a specific disclosure; legal review sign-off.",
    "Before 2026-12-10, then on ADM change",
    "ADM inventory, privacy-policy diff, legal sign-off",
    ["OAIC APP 1.7-1.9", "AU Privacy Act reforms", "ISO 42001 A.8.2"],
    [], [SRC["oaic"]],
    "A dated, enforceable obligation with a fixed commencement — the most concrete AI compliance deliverable in the Australian market right now."),

ctl("Contestability and human appeal route", "GOVERN", A[8],
    "Fairness and consumer-harm risk from automated decisions", "Established",
    "A published process for people affected by AI-influenced decisions to challenge the outcome and reach a human with authority to change it.",
    "Add an appeal path to every rights-affecting decision flow; staff it with humans who can overturn; track volumes and overturn rates.",
    "Head of Customer / Ombudsman liaison",
    "Mystery-shop the appeal route; measure time-to-human and overturn handling.",
    "Continuous; quarterly metrics",
    "Process doc, appeal metrics, overturn samples",
    ["AU VAISS Guardrail 7", "ISO 42001 A.8.3", "EU AI Act Art. 86 direction"],
    [], [SRC["vaiss"]],
    "Overturn rates are the single best early-warning metric for model harm — and regulators treat a dead-end appeal route as an aggravating factor."),

ctl("Supplier AI due-diligence and contract schedule", "GOVERN", A[10],
    "Third-party and supply-chain risk", "Established",
    "Standard due-diligence and contract clauses for AI suppliers: security posture, data use, model change notice, eval evidence, incident notification, exit rights.",
    "Build an AI supplier questionnaire and a contract schedule (data-use limits, change notice, audit rights); apply to new deals and top existing suppliers by exposure.",
    "Procurement / Vendor Risk",
    "Sample recent AI contracts for schedule inclusion; test a supplier change-notification path.",
    "Per procurement; annual top-supplier review",
    "Questionnaires, executed schedules, review log",
    ["ISO 42001 A.10.3", "CSA AICM: Supply Chain Management", "NIST AI RMF GOVERN 6", "AU VAISS Guardrail 8"],
    [], [SRC["aicm"], SRC["vaiss"]],
    "Most enterprise AI risk is inherited from suppliers — the contract schedule is where inherited risk becomes manageable."),

ctl("Customer responsibility allocation for AI services", "GOVERN", A[10],
    "Third-party accountability-gap risk", "Emerging",
    "Explicit allocation of AI responsibilities between provider and customer (shared-responsibility model): who evaluates, who monitors, who handles incidents.",
    "Adopt a shared-responsibility matrix per AICM's SSRM pattern for each AI service sold or bought; attach to contracts and onboarding.",
    "Product / Legal",
    "Review the matrix for gaps where neither party owns a duty; test one incident scenario across the boundary.",
    "Per service; annual review",
    "Responsibility matrix, contract references",
    ["ISO 42001 A.10.2 / A.10.4", "CSA AICM SSRM", "AU VAISS Guardrail 8"],
    [], [SRC["aicm"]],
    "The accountability gap between AI provider and deployer is where incidents fall through — the matrix closes it on paper before it happens in production."),

ctl("Model and vendor concentration limits with exit plans", "GOVERN", A[10],
    "Operational concentration and continuity risk", "Emerging",
    "Defined tolerance for dependence on any single model provider, with tested exit and substitution plans for critical AI services.",
    "Map critical workflows to model dependencies; set concentration triggers; maintain substitution runbooks (alternate model, degraded mode) and test annually.",
    "COO / Vendor Risk",
    "Tabletop a forced provider exit (pricing, outage, or access suspension) and measure recovery.",
    "Annual test",
    "Dependency map, exit runbooks, test report",
    ["APRA CPS 230 lens", "CSA AICM: Business Continuity", "ISO 42001 A.10.3"],
    [], [SRC["apra"], SRC["aicm"]],
    "Model access can vanish overnight — recent frontier-model suspensions made this a board question; a tested fallback is the answer."),

ctl("AI workforce competence and role-based training", "GOVERN", A[4],
    "Human-capability and misuse risk", "Established",
    "Role-appropriate AI training: builders on secure development, reviewers on failure modes, all staff on acceptable use and disclosure.",
    "Define competence requirements per role; deliver and track training; refresh when tooling or obligations change.",
    "HR / L&D with CISO",
    "Training completion plus a practical assessment for high-risk roles.",
    "Annual; on role change",
    "Competence matrix, completion records, assessments",
    ["ISO 42001 A.4.6", "CSA AICM: Human Resources", "NIST AI RMF GOVERN 4"],
    [], [SRC["iso"], SRC["aicm"]],
    "Controls fail at the human layer first — competence records are also the first thing 42001 auditors sample."),

ctl("Stakeholder engagement and fairness review", "GOVERN", A[5],
    "Societal impact and fairness risk", "Emerging",
    "Structured engagement with affected stakeholders — customers, workers, vulnerable groups — feeding diversity, inclusion, and fairness needs into AI decisions.",
    "For high-impact systems, run stakeholder consultation as part of the impact assessment; record needs and design responses; report outcomes to governance.",
    "Head of AI Governance / Community liaison",
    "Check consultation records exist for high-impact deployments and influenced design decisions.",
    "Per high-impact deployment",
    "Consultation records, impact assessment annex",
    ["AU VAISS Guardrail 10", "ISO 42001 A.5.4-A.5.5", "NIST AI RMF GOVERN 5"],
    [], [SRC["vaiss"], SRC["iso"]],
    "The guardrail organisations skip most — doing it visibly differentiates, and regulators increasingly expect evidence of it for high-risk uses."),

ctl("AI liability, insurance, and disclosure review", "GOVERN", A[2],
    "Legal liability and financial exposure risk", "Emerging",
    "Periodic review of AI liability exposure: contract warranties, insurance cover and AI exclusions, and market disclosure obligations.",
    "Annually review policies for AI exclusions; align contract warranties with actual system performance; brief the disclosure committee on material AI risks.",
    "General Counsel / CFO",
    "Trace a hypothetical AI failure through contracts and policies to find who pays.",
    "Annual",
    "Coverage review, warranty register, disclosure minutes",
    ["NIST AI RMF GOVERN 1 / 6"],
    [], [SRC["nist"]],
    "Insurers are quietly adding AI exclusions — most organisations discover coverage gaps at claim time; the review moves that discovery forward."),

# ═════════════════════════ MAP ═════════════════════════
ctl("AI system inventory with owners and risk tiers", "MAP", A[4],
    "Ungoverned AI and shadow-adoption risk", "Established",
    "A single live register of all AI systems and use cases — including embedded and supplier AI — each with a named owner, purpose, data touched, and risk tier.",
    "Consolidate procurement, architecture, and survey data into one register; tier by impact (EU AI Act classes or equivalent); make it a gate for deployment and change.",
    "Head of AI Governance / EA",
    "Reconcile the register against network telemetry, SSO logs, and expense data to find unregistered AI.",
    "Continuous; quarterly attestation",
    "Register export, reconciliation report, owner attestations",
    ["ISO 42001 A.4.2", "NIST AI RMF MAP 1", "AU VAISS Guardrail 2", "EU AI Act Art. 6 classes"],
    [], [SRC["iso"], SRC["vaiss"]],
    "Every engagement starts here: if the inventory is wrong, every downstream control inherits the error."),

ctl("Shadow-AI discovery sweep", "MAP", A[4],
    "Shadow AI and data-leakage risk", "Emerging",
    "Active discovery of unapproved AI use via SSO, CASB/proxy, expense, and browser-extension telemetry, feeding the inventory and acceptable-use enforcement.",
    "Run quarterly discovery across telemetry sources; triage findings into approve/migrate/block; report trend to governance.",
    "CISO",
    "Seed a known unapproved tool and verify the sweep finds it.",
    "Quarterly",
    "Sweep report, triage decisions, trend metrics",
    ["CSA AICM: Universal Endpoint Management", "NIST AI RMF MAP 1"],
    ["CASB / SSPM tooling"], [SRC["aicm"]],
    "Shadow AI is typically 3-10x the approved estate — the sweep converts an unknown into a managed number."),

ctl("AI impact assessment (individuals and society)", "MAP", A[5],
    "Harm to individuals and societal impact risk", "Established",
    "A gated impact assessment for new or materially changed AI systems covering effects on individuals, groups, and society, with documented outcomes and mitigations.",
    "Adopt an AIA template (DTA/ISO 42005 pattern); trigger on new use cases and material changes; require sign-off before build proceeds; file with the inventory.",
    "System owner with Privacy / Ethics review",
    "Sample high-tier systems for completed, current AIAs; check mitigations landed in design.",
    "Per system; refresh on material change",
    "Completed AIAs, sign-offs, mitigation trace",
    ["ISO 42001 A.5.2-A.5.5", "ISO/IEC 42005", "NIST AI RMF MAP 5", "AU VAISS Guardrail 2"],
    [], [SRC["iso"], SRC["vaiss"]],
    "The AIA is where 'we considered the risk' becomes provable — and A.5.5's societal lens is the part nobody does, so doing it shows."),

ctl("Data mapping and provenance for AI systems", "MAP", A[7],
    "Data quality, privacy, and provenance risk", "Established",
    "Documented lineage for data used to train, tune, ground, or prompt each AI system: source, licence, consent basis, quality checks, and preparation steps.",
    "For each inventoried system, record data sources and legal basis; apply quality gates on acquisition; keep provenance metadata with datasets.",
    "Chief Data Officer",
    "Trace three production outputs back to their data sources and licences.",
    "Per system; annual re-verification",
    "Lineage records, licence register, quality-gate logs",
    ["ISO 42001 A.7.2-A.7.6", "CSA AICM: Data Security and Privacy", "AU VAISS Guardrail 3"],
    [], [SRC["iso"], SRC["aicm"]],
    "Copyright and consent claims land here — provenance you can produce in discovery is worth multiples of provenance you reconstruct under subpoena."),

ctl("Agentic workflow and tool-access mapping", "MAP", A[4],
    "Agentic AI security and privilege risk", "Emerging",
    "A map of every agent: what tools it can call, what credentials it holds, what systems it can write to, and which humans supervise it.",
    "Extend the inventory with an agent annex — tools, scopes, credentials, memory stores, inter-agent links; review before any new tool is granted.",
    "Platform Engineering / CISO",
    "Diff mapped permissions against actual granted scopes in the IAM system.",
    "Continuous; monthly diff",
    "Agent map, IAM reconciliation, approval records",
    ["OWASP ASI03 Agent Identity & Privilege Abuse", "CSA AICM: IAM", "NIST AI RMF MAP 1"],
    [], [SRC["owasp_asi"], SRC["aicm"]],
    "You cannot contain what you haven't mapped — the agent map is the prerequisite for every agentic control below it."),

ctl("AI supply-chain component register (models, MCP, libraries)", "MAP", A[10],
    "AI supply-chain compromise risk", "Emerging",
    "An AI bill of materials: base models, fine-tunes, embeddings, MCP servers, agent frameworks, and libraries per system, with versions and sources.",
    "Generate and store AI-BOMs per system; subscribe components to vulnerability feeds; block unregistered components in CI.",
    "Platform Engineering",
    "Pick a disclosed vulnerability (e.g. an MCP SDK CVE) and time how fast affected systems are identified.",
    "Continuous via CI; monthly report",
    "AI-BOMs, feed subscriptions, CI policy",
    ["OWASP ASI04 Supply Chain", "CSA AICM: Supply Chain Management", "NIST SSDF"],
    ["SBOM/AI-BOM tooling"], [SRC["owasp_asi"], SRC["ssdf"]],
    "The MCP-era supply chain moves faster than quarterly reviews — the register is what turns a CVE headline into a same-day impact list."),

ctl("Use-case intake and risk-tier triage gate", "MAP", A[6],
    "Ungoverned deployment risk", "Established",
    "A single front door for proposed AI uses that assigns risk tier, required controls, and approval path before any build or purchase.",
    "Stand up an intake form wired to the inventory; auto-assign control requirements by tier; route high tiers to the governance committee.",
    "Head of AI Governance",
    "Attempt to deploy a test use case around the gate and confirm it is caught.",
    "Continuous",
    "Intake records, tier decisions, bypass alerts",
    ["ISO 42001 A.6.1.2-A.6.1.3", "NIST AI RMF MAP 2-3", "AU VAISS Guardrail 2"],
    [], [SRC["iso"], SRC["vaiss"]],
    "One door in means the inventory stays true by construction, not by audit."),

# ═════════════════════════ MEASURE ═════════════════════════
ctl("Pre-deployment evaluation gate with acceptance criteria", "MEASURE", A[6],
    "Model performance and reliability risk", "Established",
    "No AI system ships without passing documented evaluations — task performance, safety behaviours, robustness — against pre-agreed acceptance criteria.",
    "Define eval suites per use case (accuracy, refusal, injection resistance); wire into CI/CD as a release gate; record results with the system version.",
    "Engineering lead / QA",
    "Review release records for eval evidence; attempt a release with failing evals and confirm the gate blocks.",
    "Every release",
    "Eval definitions, gate logs, versioned results",
    ["ISO 42001 A.6.2.4", "NIST AI RMF MEASURE 2", "AU VAISS Guardrail 4"],
    ["inspect_ai", "promptfoo", "Giskard"], [SRC["nist"], SRC["vaiss"]],
    "'Test before you ship, and keep the receipts' — the single control that converts AI quality from vibes to evidence."),

ctl("Adversarial red-teaming (LLM and agentic)", "MEASURE", A[6],
    "AI security and prompt-injection risk", "Established",
    "Periodic adversarial testing against the OWASP LLM and Agentic Top 10: prompt injection, goal hijack, tool misuse, memory poisoning, data exfiltration.",
    "Run structured red-team campaigns per major release and quarterly on critical systems; track findings to closure; rotate scenarios with the threat landscape.",
    "Security testing / external specialists",
    "Independent re-test of closed findings; coverage check against OWASP categories.",
    "Quarterly for critical systems; every major release",
    "Campaign reports, finding register, closure evidence",
    ["OWASP LLM Top 10 2025", "OWASP ASI01-ASI10", "MITRE ATLAS", "NIST AI RMF MEASURE 2.7"],
    ["garak", "PyRIT", "promptfoo"], [SRC["owasp_llm"], SRC["owasp_asi"], SRC["atlas"]],
    "The eval gate proves it works; red-teaming proves it fails safely — buyers and regulators now ask for both."),

ctl("Bias and fairness testing on decision systems", "MEASURE", A[5],
    "Fairness, discrimination, and harm risk", "Established",
    "Statistical testing of rights-affecting systems across protected attributes, with thresholds, remediation duties, and re-test cadence.",
    "Select fairness metrics per decision type; test pre-deployment and on data drift; document accepted disparities with justification and sign-off.",
    "Data science lead / Ethics review",
    "Independent reproduction of fairness results; check remediation actions for breached thresholds.",
    "Pre-deployment; semi-annual re-test",
    "Test reports, threshold decisions, remediation log",
    ["ISO 42001 A.5.4", "NIST AI RMF MEASURE 2.11", "ISO/IEC TR 24027"],
    ["Fairlearn", "Aequitas"], [SRC["nist"], SRC["iso"]],
    "Discrimination claims are the most litigated AI harm — documented testing with thresholds is both the defence and the early warning."),

ctl("Production monitoring: drift, quality, and anomaly detection", "MEASURE", A[6],
    "Operational degradation and drift risk", "Established",
    "Continuous monitoring of deployed AI for input drift, output quality, cost, latency, and behavioural anomalies, with alert thresholds and escalation.",
    "Instrument systems with quality metrics and drift detectors; set alert thresholds tied to the risk tier; route alerts to a staffed queue.",
    "SRE / ML Ops",
    "Inject synthetic drift and verify detection-to-escalation within SLA.",
    "Continuous",
    "Dashboards, alert history, escalation records",
    ["ISO 42001 A.6.2.6", "NIST AI RMF MEASURE 2.4 / MANAGE 4", "AU VAISS Guardrail 4"],
    [], [SRC["iso"], SRC["vaiss"]],
    "Models rot silently — drift monitoring is the smoke detector, and 'the system once deployed' half of Guardrail 4 that most orgs skip."),

ctl("Agent action logging and behavioural baselining", "MEASURE", A[6],
    "Agentic security and audit-trail risk", "Emerging",
    "Tamper-evident logs of every agent action — prompts, tool calls, credentials used, outputs — with baseline models flagging behavioural deviation.",
    "Log all agent tool calls with identity and rationale; retain per evidence rules; baseline normal behaviour and alert on deviation (new tools, odd hours, bulk access).",
    "CISO / Platform",
    "Reconstruct a full agent session cold from logs; test anomaly alerts with a scripted deviation.",
    "Continuous",
    "Log samples, retention config, anomaly alerts",
    ["ISO 42001 A.6.2.8", "OWASP ASI mitigations (observability)", "CSA AICM: Logging and Monitoring"],
    [], [SRC["owasp_asi"], SRC["aicm"]],
    "When an agent does something wrong, the first question is 'what exactly did it do?' — this control is the difference between an answer and a shrug."),

ctl("Independent AI assurance review", "MEASURE", A[6],
    "Assurance and audit-credibility risk", "Emerging",
    "Periodic independent review (internal audit or external) of high-tier AI systems against the control library, with findings tracked to closure.",
    "Commission reviews on a risk-based cycle; scope against ISO 42001 and this library; publish summary results to the board.",
    "Internal Audit / external assurer",
    "The review is the test; meta-check finding closure rates and repeat findings.",
    "Annual for high-tier systems",
    "Review reports, finding register, board summary",
    ["ISO 42001 Clause 9 / A.6", "CSA AICM: Audit and Assurance", "AU VAISS Guardrail 9"],
    [], [SRC["aicm"], SRC["vaiss"]],
    "42001 certification demand is arriving — organisations that have run independent reviews walk into certification; the rest walk into findings."),

ctl("Model change regression and capability testing", "MEASURE", A[6],
    "Model-update regression risk", "Emerging",
    "Regression testing when a model, prompt, or provider version changes — including silent upstream model updates — before the change reaches production.",
    "Pin model versions where possible; maintain regression suites replaying golden tasks and safety probes; subscribe to provider change notices and re-test on change.",
    "ML Ops",
    "Simulate a provider model swap in staging and verify the regression suite catches behaviour change.",
    "Every change; weekly canary replay",
    "Version pins, regression results, change-notice log",
    ["ISO 42001 A.6.2.4-A.6.2.5", "CSA AICM: Change Control", "NIST AI RMF MEASURE 2"],
    ["promptfoo", "inspect_ai"], [SRC["aicm"], SRC["nist"]],
    "Providers update models under your feet — the regression suite is how you find out before your customers do."),

ctl("AI incident metrics and near-miss tracking", "MEASURE", A[8],
    "Governance risk: incident learning and disclosure", "Emerging",
    "Systematic capture of AI incidents and near-misses with severity taxonomy, trend metrics, and feeds into risk scoring and the public incident record where required.",
    "Extend incident taxonomy for AI failure modes; log near-misses from monitoring and staff reports; review trends quarterly and adjust controls.",
    "Risk / Incident Management",
    "Sample incidents for taxonomy quality; check near-miss volume (zero means it isn't working).",
    "Continuous; quarterly trend review",
    "Incident register, trend report, control adjustments",
    ["ISO 42001 A.8.4", "NIST AI RMF MEASURE 3", "AIID pattern"],
    [], [SRC["nist"]],
    "Near-misses are free lessons — the register turns them into control improvements before they become AIID entries."),

# ═════════════════════════ MANAGE ═════════════════════════
ctl("Least-privilege, short-lived agent identities", "MANAGE", A[6],
    "Agentic AI security risk: identity and privilege abuse", "Emerging",
    "Every agent runs under its own scoped, short-lived identity — never a shared service account or a human's credentials — with permissions matched to task.",
    "Issue per-agent identities via the IAM platform; scope tokens to task and TTL; prohibit credential pass-through; review scopes monthly against the agent map.",
    "IAM / Platform Engineering",
    "Attempt privilege escalation and lateral tool use from a test agent; audit token TTLs and scopes.",
    "Continuous; monthly scope review",
    "IAM config, scope audit, escalation-test report",
    ["OWASP ASI03", "CSA AICM: IAM", "NIST AI RMF MANAGE 1"],
    [], [SRC["owasp_asi"], SRC["aicm"]],
    "The number-one agentic mitigation across every 2026 framework — scoped identity is to agents what least privilege was to users."),

ctl("Agent sandboxing with egress control", "MANAGE", A[6],
    "Agentic AI security risk: unexpected code execution and exfiltration", "Emerging",
    "Agents that execute code or browse run inside sandboxes with default-deny network egress, resource limits, and no route to production secrets.",
    "Containerise agent execution; allow-list egress destinations; separate secrets brokers; kill long-running or resource-anomalous sessions automatically.",
    "Platform Engineering",
    "Red-team the sandbox: attempt exfiltration, secret access, and egress to unlisted hosts.",
    "Continuous; quarterly sandbox test",
    "Sandbox config, egress rules, escape-test report",
    ["OWASP ASI05 Unexpected Code Execution", "CSA AICM: Infrastructure Security", "MITRE ATLAS mitigations"],
    [], [SRC["owasp_asi"], SRC["atlas"]],
    "The Cursor-deletes-the-database class of incident is a sandboxing failure — containment converts catastrophic into annoying."),

ctl("Human approval gates for high-impact actions", "MANAGE", A[9],
    "Safety risk from autonomous high-impact actions", "Established",
    "Defined action classes (payments, deletions, external comms, production changes) that agents cannot execute without informed human approval, with friction proportional to impact.",
    "Classify actions by reversibility and impact; require out-of-band approval for the top class; log approvals with the approver's identity; audit for rubber-stamping.",
    "System owner / Operations",
    "Attempt each gated action class without approval; measure approval quality (time-to-review, rejection rate).",
    "Continuous; monthly rubber-stamp audit",
    "Action classification, approval logs, audit report",
    ["AU VAISS Guardrail 5", "ISO 42001 A.9.2", "OWASP ASI09 mitigation", "NIST AI RMF MANAGE 2"],
    [], [SRC["vaiss"], SRC["owasp_asi"]],
    "Meaningful human oversight is the guardrail regulators quote most — approval logs are what make 'meaningful' provable, and rubber-stamp audits keep it honest."),

ctl("Kill switch and graceful degradation", "MANAGE", A[9],
    "Operational risk from runaway or cascading agent failures", "Established",
    "A tested ability to pause or stop any AI system quickly — including mid-task agents — with a defined degraded mode so the business keeps running.",
    "Implement per-system stop controls (feature flags, queue drains, credential revocation); document degraded-mode runbooks; test the full stop path, not just the flag.",
    "Operations / SRE",
    "Quarterly kill-switch drill on a production-like environment, measuring time-to-stop and degraded-mode function.",
    "Quarterly drill",
    "Stop procedures, drill reports, degraded-mode runbooks",
    ["ISO 42001 A.9.2", "OWASP ASI08 Cascading Failures", "AU VAISS Guardrail 5"],
    [], [SRC["owasp_asi"], SRC["vaiss"]],
    "Everyone claims they can turn it off; the drill report proves it — and it's the first question after any agentic incident."),

ctl("Prompt-injection defence in depth", "MANAGE", A[6],
    "Security risk: prompt injection and goal hijack", "Emerging",
    "Layered defences against direct and indirect injection: input isolation, content labelling, output validation, tool-call constraints, and injection-aware monitoring.",
    "Segregate untrusted content from instructions; validate tool calls against task intent; strip/label external content; monitor for injection signatures; assume breach and contain blast radius via least privilege.",
    "Engineering / Security",
    "Red-team with current injection corpora (direct, indirect, multimodal); measure block and detection rates.",
    "Continuous; re-test quarterly",
    "Architecture doc, injection test results, monitoring rules",
    ["OWASP LLM01 Prompt Injection", "OWASP ASI01 Goal Hijack", "MITRE ATLAS"],
    ["garak", "PyRIT"], [SRC["owasp_llm"], SRC["owasp_asi"]],
    "Injection is unsolved — the honest control is defence in depth plus containment, and buyers now ask exactly how you've layered it."),

ctl("Memory and context integrity protection", "MANAGE", A[6],
    "Security risk: memory and context poisoning", "Emerging",
    "Agent memory and RAG stores are partitioned by trust level, integrity-checked, auditable, and purgeable — poisoned context can be found and flushed.",
    "Partition memory by source trust; sign or checksum persistent memory; log writes with provenance; build a verified purge-and-rebuild path for stores.",
    "Platform Engineering",
    "Inject a poisoned memory entry in staging; verify detection, audit trail, and clean purge.",
    "Continuous; semi-annual purge test",
    "Memory architecture, write logs, purge-test report",
    ["OWASP ASI06 Memory & Context Poisoning", "OWASP LLM08 Vector Weaknesses"],
    [], [SRC["owasp_asi"], SRC["owasp_llm"]],
    "Poisoned memory persists across sessions — without a purge path, one successful injection becomes a permanent implant."),

ctl("Inter-agent communication authentication", "MANAGE", A[6],
    "Insecure agent-to-agent communication risk", "Emerging",
    "Agent-to-agent and agent-to-MCP traffic is mutually authenticated, authorised per capability, and monitored — no anonymous agents on the internal bus.",
    "Require mTLS or signed messages between agents; authorise by capability not identity alone; log and baseline inter-agent traffic.",
    "Platform / Network Security",
    "Attempt to introduce a rogue agent onto the bus; verify rejection and alerting.",
    "Continuous",
    "Auth config, traffic baselines, rogue-agent test",
    ["OWASP ASI07 Insecure Inter-Agent Communication", "CSA AICM: Application & Interface Security"],
    [], [SRC["owasp_asi"], SRC["aicm"]],
    "Multi-agent systems recreate the flat-network problem — mutual auth now is cheaper than segmentation retrofits later."),

ctl("AI vulnerability and patch management (MCP, frameworks, models)", "MANAGE", A[6],
    "AI supply-chain vulnerability risk", "Established",
    "AI-stack components — MCP servers, agent frameworks, inference servers, model files — are covered by vulnerability management with defined patch SLAs.",
    "Add AI components to the vuln programme via the AI-BOM; set SLAs by exposure; subscribe to AI-specific advisories; scan model artifacts for malicious payloads.",
    "Vulnerability Management",
    "Measure SLA compliance; verify a recent AI-stack CVE was identified and patched within SLA.",
    "Continuous; monthly SLA report",
    "Scan coverage, SLA metrics, advisory subscriptions",
    ["CSA AICM: Threat & Vulnerability Management", "OWASP ASI04", "NIST SSDF"],
    ["dependency scanners", "model scanners"], [SRC["aicm"], SRC["ssdf"]],
    "MCP-era CVEs land monthly — the question in every post-incident review is whether the component was even in scope."),

ctl("Data minimisation, retention, and deletion for AI", "MANAGE", A[7],
    "Privacy and data-protection risk", "Established",
    "AI systems collect and retain only necessary personal data, with enforced retention limits and a tested deletion path covering prompts, logs, and derived stores.",
    "Apply minimisation at design; set retention per data class including vendor-side; verify deletion propagates to embeddings, caches, and logs.",
    "Privacy Officer / Data Engineering",
    "Exercise a deletion request end-to-end and verify removal from all AI stores.",
    "Continuous; annual deletion test",
    "Retention schedule, deletion-test evidence, vendor attestations",
    ["ISO 42001 A.7", "OAIC APP guidance", "CSA AICM: Data Security & Privacy Lifecycle"],
    [], [SRC["oaic"], SRC["aicm"]],
    "Vector stores are where deletion promises go to die — proving propagation is a differentiating privacy review."),

ctl("Output filtering and sensitive-data leak prevention", "MANAGE", A[6],
    "Privacy and security risk: sensitive information disclosure", "Established",
    "Model outputs pass through filtering for sensitive data (PII, secrets, client data) and policy violations before reaching users or downstream systems.",
    "Deploy output classifiers and DLP on AI egress paths; redact or block on detection; log events for tuning; cover tool outputs, not just chat.",
    "Security Engineering",
    "Seed canary secrets and verify egress detection across chat, API, and tool paths.",
    "Continuous; monthly canary test",
    "Filter config, detection metrics, canary results",
    ["OWASP LLM02 Sensitive Information Disclosure", "CSA AICM: Data Security", "NIST AI 600-1"],
    [], [SRC["owasp_llm"], SRC["genai_profile"]],
    "Models leak what they were given — egress filtering is the compensating control for every upstream over-share."),

ctl("Content provenance and AI-generation disclosure", "MANAGE", A[8],
    "Synthetic-media, deepfake, and trust risk", "Emerging",
    "AI-generated content the organisation publishes is labelled and carries provenance credentials (C2PA), and users are told when they interact with AI.",
    "Adopt C2PA signing in content pipelines; label AI interactions per VAISS Guardrail 6; verify inbound provenance where decisions rely on media authenticity.",
    "Comms / Product",
    "Verify published assets carry valid credentials; check disclosure surfaces in AI-facing journeys.",
    "Continuous",
    "Signing config, disclosure inventory, verification samples",
    ["C2PA", "AU VAISS Guardrail 6", "EU AI Act Art. 50 transparency"],
    [], [SRC["c2pa"], SRC["vaiss"]],
    "Deepfake fraud made authenticity a control, not a feature — provenance signing is cheap insurance for brand trust."),

ctl("Synthetic-media impersonation response runbook", "MANAGE", A[8],
    "Deepfake fraud and impersonation risk", "Emerging",
    "A prepared response for deepfakes of executives, brands, or customers: detection channels, takedown routes, out-of-band verification, and comms templates.",
    "Pre-register takedown contacts (platforms, eSafety); train finance and exec assistants on out-of-band verification; drill the runbook against a simulated CEO-fraud deepfake.",
    "CISO / Corporate Affairs",
    "Annual simulation: deepfake voice request through payment workflow, measuring detection and verification behaviour.",
    "Annual drill",
    "Runbook, drill report, takedown contact register",
    ["eSafety takedown routes", "MITRE ATLAS", "AU VAISS Guardrail 5"],
    [], [SRC["esafety"], SRC["atlas"]],
    "Every finance team will face an AI voice-fraud attempt — the drill is what makes the payment clerk hang up."),

ctl("AI incident response plan with agentic playbooks", "MANAGE", A[8],
    "Security incident readiness and containment risk", "Established",
    "Incident response extended for AI failure modes — injection compromise, agent misuse, model theft, harmful output at scale — with roles, comms, and regulator notification mapped.",
    "Add AI playbooks to the IR plan (contain = revoke agent credentials, quarantine memory, flip kill switch); map notification duties (OAIC, APRA, eSafety); exercise annually.",
    "CISO / IR lead",
    "Tabletop an agentic compromise end-to-end including regulator-notification decision.",
    "Annual exercise",
    "IR plan annex, exercise report, notification matrix",
    ["ISO 42001 A.8.4", "CSA AICM: Security Incident Management", "OWASP ASI08"],
    [], [SRC["aicm"], SRC["owasp_asi"]],
    "Generic IR plans assume human attackers — agent incidents need agent-shaped containment steps, decided before 2am."),

ctl("Model registry with rollback and deprecation", "MANAGE", A[6],
    "Operational deployment and rollback risk", "Established",
    "Every production model/prompt configuration is versioned in a registry with one-step rollback and a managed deprecation path for retiring systems.",
    "Register models, prompts, and configs with approvals; keep last-known-good deployable; define deprecation criteria and user-migration duties.",
    "ML Ops",
    "Execute a rollback drill from a bad deploy; verify a retired system is actually unreachable.",
    "Rollback drill quarterly",
    "Registry records, rollback drill logs, deprecation checklist",
    ["ISO 42001 A.6.2.5-A.6.2.6", "CSA AICM: Change Control", "AU VAISS Guardrail 4"],
    [], [SRC["aicm"], SRC["vaiss"]],
    "Fast rollback is the cheapest mitigation for almost every model failure — and deprecation is where zombie systems breed incidents."),

ctl("Business continuity for AI-dependent processes", "MANAGE", A[6],
    "Operational continuity and resilience risk", "Emerging",
    "Business processes that depend on AI have continuity plans for model outage, provider suspension, or forced rollback — including human-process fallbacks.",
    "Identify AI-critical processes from the inventory; document manual/degraded alternatives; set RTOs; test the human fallback annually.",
    "COO / BCM",
    "Run a process with the AI disabled for a working session and measure throughput and error.",
    "Annual per critical process",
    "BC plans, fallback test reports, RTO evidence",
    ["APRA CPS 230", "CSA AICM: Business Continuity & Operational Resilience", "ISO 42001 A.6.2.6"],
    [], [SRC["apra"], SRC["aicm"]],
    "When AI becomes the process, its outage is a business outage — CPS 230 already expects this for regulated entities."),

ctl("Vulnerable-user and child-safety safeguards", "MANAGE", A[9],
    "Safety and trust risk to vulnerable users and children", "Emerging",
    "Consumer-facing AI implements age assurance, harm-pattern detection, crisis escalation, abuse reporting, and moderation tuned for vulnerable users and minors.",
    "Apply eSafety codes: age assurance where required, self-harm and grooming pattern detection with human escalation, visible reporting, and periodic safety audits of conversations.",
    "Product / Trust & Safety",
    "Safety-test with scripted vulnerable-user scenarios; verify escalation and reporting paths fire.",
    "Continuous; quarterly safety audit",
    "Safety test results, escalation logs, audit reports",
    ["eSafety industry codes", "AU Social Media Minimum Age", "ISO 42001 A.9.2"],
    [], [SRC["esafety"]],
    "Companion-bot harms are this year's enforcement theme in Australia — these safeguards are moving from ethics to obligation."),

ctl("Environmental footprint measurement and workforce transition", "MANAGE", A[5],
    "Societal impact risk: environment and workforce", "Emerging",
    "The organisation measures AI compute/energy footprint and manages workforce impacts of AI-driven change with reskilling and consultation.",
    "Track energy/emissions for material AI workloads and include in sustainability reporting; pair AI-driven role changes with consultation and reskilling budgets.",
    "Sustainability / CHRO",
    "Reconcile reported AI footprint against cloud billing; audit reskilling uptake for affected roles.",
    "Annual reporting cycle",
    "Footprint methodology, sustainability report extract, reskilling records",
    ["ISO 42001 A.5.5", "NIST AI RMF GOVERN 5 / MAP 5", "AU VAISS Guardrail 10"],
    [], [SRC["iso"], SRC["vaiss"]],
    "Societal impact is the emptiest cell in most control libraries — measurable footprint and workforce-transition evidence fills it credibly."),

# ═══════════════════ build ═══════════════════
def slugify(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return re.sub(r"-{2,}", "-", s)[:60].strip("-")

def main():
    d = json.loads(DATA.read_text())
    old = d.get("controls", [])
    for c in C:
        c["id"] = slugify(c["name"])
        c["firstSeen"] = TODAY
        c["lastUpdated"] = TODAY
        c["status"] = "new"
        c["owner"] = c.get("owner", "")
    ids = [c["id"] for c in C]
    assert len(ids) == len(set(ids)), "duplicate control ids"
    d["controls"] = C
    d["changelog"] = [{
        "date": TODAY,
        "title": "Control Library rebuilt from best-practice sources",
        "details": (f"Replaced {len(old)} accumulated controls with a curated library of {len(C)} canonical controls "
                    "sourced from ISO/IEC 42001 Annex A, NIST AI RMF, CSA AICM v1, OWASP LLM Top 10 2025 and "
                    "Agentic Top 10 2026, MITRE ATLAS, Australia's Voluntary AI Safety Standard, and tracked "
                    "AU obligations (OAIC ADM, APRA, eSafety, DTA). Each control carries implementation, testing, "
                    "evidence, framework crosswalks, primary sources, and a practice lens."),
    }] + d.get("changelog", [])
    DATA.write_text(json.dumps(d, indent=1, ensure_ascii=False))
    from collections import Counter
    print(f"controls: {len(old)} -> {len(C)}")
    print("functions:", dict(Counter(c['nistFunction'] for c in C)))
    print("areas:", dict(sorted(Counter(c['iso42001Area'] for c in C).items())))
    themes = Counter()
    for c in C:
        themes[c['risk']] = themes[c['risk']] + 0  # noop, coverage computed client-side
    print("all controls have sources:", all(c.get('sources') for c in C))
    print("all controls have soWhat:", all(c.get('soWhat') for c in C))

if __name__ == "__main__":
    main()
